//
//  XC21Models.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class XC21Models: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _country: String?
    var _email: String?
    var _firstname: String?
    var _heightCm: String?
    var _heightFt: String?
    var _mobile: String?
    var _surname: String?
    
    class func dynamoDBTableName() -> String {

        return "xc-mobilehub-REDACTED"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_country" : "Country",
               "_email" : "Email",
               "_firstname" : "Firstname",
               "_heightCm" : "Height_cm",
               "_heightFt" : "Height_ft",
               "_mobile" : "Mobile",
               "_surname" : "Surname",
        ]
    }
}
