#!/bin/bash
yum update -yumyum install -y httpd
systemctl start httpd.service
systemctl enable httpd.service
EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availablity-zone)
echo "<h1>Hello World from $(hostname -f) in AZ $EC@_AVAIL_ZONE </h1>" > /var/www/html/index.html