#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd.service
systemctl enable httpd.service
EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availablity-zone)
echo "<h1>Hello World from $(hostname -f) in AZ $EC@_AVAIL_ZONE </h1>" > /var/www/html/index.html




sudo yum update -y
sudo yum install -y httpd
sudo systemctl start httpd.service
sudo systemctl enable httpd.service
sudo EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availablity-zone)
sudo echo "<h1>Hello World from $(hostname -f) in AZ $EC@_AVAIL_ZONE </h1>" > /var/www/html/index.html