# podfile3


platform :ios, '9.0'

target 'XC21' do
  use_frameworks!
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSUserPoolsSignIn', '~> 2.6.13'
  pod 'AWSAuthUI', '~> 2.6.13'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSDynamoDB', '~> 2.6.13'
  pod 'AWSS3', '~> 2.6.13'   # For file transfers
  pod 'AWSCognito', '~> 2.6.13'   #For data sync
  pod 'AWSPinpoint', '~> 2.6.13'    # For Analytics (Streaming)
end
